import { chromium } from 'playwright'
import { serve } from './serve.mjs'
const server = await serve()
const browser = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required','--enable-unsafe-swiftshader','--use-gl=swiftshader'] })
const page = await browser.newPage({ viewport: { width: 900, height: 700 } })
await page.addInitScript(() => localStorage.setItem('fretline:v1', JSON.stringify({ settings: { noFail: true, difficulty: 'expert', quality: 'baixa', noteSpeed: 8 } })))
await page.goto(`${server.url}/?debug&lowfx&shot=wide`, { waitUntil: 'networkidle' })
await page.waitForTimeout(2500)
await page.getByRole('button', { name: /Tocar/ }).first().click()
await page.getByRole('heading', { name: 'Escolha a música' }).waitFor()
await page.locator('.song-row').filter({ hasText: 'Teste Local' }).first().click()
await page.getByRole('button', { name: /^Tocar em/ }).click()
await page.waitForFunction(() => !document.body.innerText.includes('Afinando'), null, { timeout: 60000 })
await page.waitForTimeout(4200)
await page.screenshot({ path: 'scripts/chord-check.png' })
await browser.close(); await server.close()
console.log('ok')
